# Generated by Django 3.2 on 2022-09-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('status', models.CharField(
                    choices=[('new', 'Новая'), ('in process', 'В процессе'), ('ready', 'Сделано')], default='new',
                    max_length=15, verbose_name='Статус')),
                ('deadline', models.DateField(default='', verbose_name='Дата выполнения')),
            ],
        ),
    ]
